import React from 'react';

export default function AgronomistDashboard({ user, onLogout }) {
  const first = user?.name?.split(' ')[0] || 'Jean';
  const inits = user?.initials || 'JD';

  return (
    <div className="page on" id="pg-dash-agro">
      <div className="dash-wrap">
        <div className="dash-sb">
          <div className="dash-sb-top"><div className="dash-sb-logo"><div className="li">🌿</div><div><div className="lt">AgriConnect</div><div className="ls">Rwanda</div></div></div></div>
          <div className="dash-nav">
            <div className="di act"><span className="dii">⊞</span><span>Dashboard</span></div>
            <div className="di"><span className="dii">📋</span><span>Appt Requests</span><span className="dib">5</span></div>
            <div className="di"><span className="dii">📅</span><span>My Appointments</span></div>
            <div className="di"><span className="dii">👥</span><span>Assigned Farmers</span></div>
            <div className="di"><span className="dii">📄</span><span>Farm Reports</span><span className="dib">3</span></div>
            <div className="di"><span className="dii">💬</span><span>Recommendations</span></div>
            <div className="di"><span className="dii">📍</span><span>Field Visits</span></div>
            <div className="di"><span className="dii">🔔</span><span>Alerts</span><span className="dib">2</span></div>
            <div className="di"><span className="dii">📚</span><span>Knowledge Base</span></div>
            <div className="di"><span className="dii">📊</span><span>Analytics</span></div>
            <div className="di"><span className="dii">✉</span><span>Messages</span><span className="dib">7</span></div>
            <div className="di"><span className="dii">👤</span><span>Profile</span></div>
            <div className="di"><span className="dii">⚙</span><span>Settings</span></div>
          </div>
          <div className="sb-prof"><div className="sb-prof-card"><div className="sb-prow"><div className="sb-av" id="agro-av">{inits}</div><div><div className="sb-pname" id="agro-name">{user?.name || 'Jean de Dieu'}</div><div className="sb-prole">Agronomist ✅</div></div></div><div className="sb-pdet">📞 +250 788 123 456</div><div className="sb-pdet" id="agro-email">✉ {user?.email || 'jean@agri.rw'}</div><button onClick={onLogout} style={{ width: '100%', marginTop: '5px', background: 'transparent', border: '0.5px solid #f87171', color: '#f87171', padding: '3px', borderRadius: '4px', fontSize: '7px', cursor: 'pointer' }}>Logout</button></div></div>
        </div>
        <div className="dash-main">
          <div className="dash-hdr">
            <div className="dash-search-wrap"><input className="dash-search" placeholder="Search farmers, reports..." /></div>
            <div className="dash-hdr-right">
              <div style={{ padding: '3px 6px', background: '#f1f5f9', borderRadius: '4px', fontSize: '8px', color: 'var(--color-text-primary)' }}>🌐 EN</div>
              <div className="hbadge">🔔<span className="hbd" style={{ background: '#ef4444' }}>2</span></div>
              <div className="hbadge">✉<span className="hbd" style={{ background: '#3b82f6' }}>7</span></div>
              <div className="huser"><div className="hav" id="dash-hav">{inits}</div><div><div className="hname" id="dash-hname">{first}</div><div className="hrole">Agronomist</div></div></div>
            </div>
          </div>
          <div className="dash-body">
            <div><div className="dash-ptitle">Agronomist Dashboard</div><div className="dash-psub">Welcome back, <span id="dash-welcome">{first}</span>. Here's your activity overview for today.</div></div>
            <div className="metrics">
              <div className="met" style={{ borderColor: '#fde68a' }}><div className="met-icon" style={{ background: '#fef3c7', color: '#d97706' }}>📋</div><div className="met-val">12</div><div className="met-label">Pending Appointments</div><div className="met-ch" style={{ color: '#d97706' }}>+3 today</div></div>
              <div className="met" style={{ borderColor: '#bfdbfe' }}><div className="met-icon" style={{ background: '#dbeafe', color: '#2563eb' }}>📅</div><div className="met-val">4</div><div className="met-label">Today's Appointments</div><div className="met-ch" style={{ color: '#2563eb' }}>2 remaining</div></div>
              <div className="met" style={{ borderColor: '#bbf7d0' }}><div className="met-icon" style={{ background: '#dcfce7', color: '#15803d' }}>✅</div><div className="met-val">34</div><div className="met-label">Reports Completed</div><div className="met-ch" style={{ color: '#15803d' }}>+8 this week</div></div>
              <div className="met" style={{ borderColor: '#e9d5ff' }}><div className="met-icon" style={{ background: '#f3e8ff', color: '#7c3aed' }}>👥</div><div className="met-val">128</div><div className="met-label">Farmers Assisted</div><div className="met-ch" style={{ color: '#7c3aed' }}>+12 month</div></div>
              <div className="met" style={{ borderColor: '#fecaca' }}><div className="met-icon" style={{ background: '#fee2e2', color: '#dc2626' }}>⚠</div><div className="met-val">7</div><div className="met-label">High Severity Cases</div><div className="met-ch" style={{ color: '#dc2626' }}>3 unresolved</div></div>
            </div>
            <div className="dash-grid2">
              <div className="dcard">
                <div className="dcard-head"><h3>Appointment Requests</h3><p>Manage incoming farmer requests</p></div>
                <table className="dtable"><thead><tr><th>Farmer</th><th>District</th><th>Crop</th><th>Issue</th><th>Severity</th><th>Status</th><th>Actions</th></tr></thead><tbody>
                  <tr><td><div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><div className="fav">CM</div><div><div style={{ fontSize: '8px', fontWeight: '500' }}>Claudine Mukamana</div><div style={{ fontSize: '7px', color: '#94a3b8' }}>APT-001</div></div></div></td><td>Gasabo</td><td>Maize</td><td>Leaf blight</td><td><span className="pill pill-r">High</span></td><td><span className="pill pill-y">Pending</span></td><td><div className="act-btns"><button className="ab" style={{ background: '#dcfce7', color: '#15803d' }}>✓</button><button className="ab" style={{ background: '#fee2e2', color: '#dc2626' }}>✗</button></div></td></tr>
                  <tr><td><div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><div className="fav">EH</div><div><div style={{ fontSize: '8px', fontWeight: '500' }}>Emmanuel Habimana</div><div style={{ fontSize: '7px', color: '#94a3b8' }}>APT-002</div></div></div></td><td>Kicukiro</td><td>Beans</td><td>Root rot</td><td><span className="pill pill-y">Medium</span></td><td><span className="pill pill-y">Pending</span></td><td><div className="act-btns"><button className="ab" style={{ background: '#dcfce7', color: '#15803d' }}>✓</button><button className="ab" style={{ background: '#fee2e2', color: '#dc2626' }}>✗</button></div></td></tr>
                  <tr><td><div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><div className="fav">VN</div><div><div style={{ fontSize: '8px', fontWeight: '500' }}>Vestine Nyirahabimana</div><div style={{ fontSize: '7px', color: '#94a3b8' }}>APT-003</div></div></div></td><td>Nyarugenge</td><td>Tomatoes</td><td>Bacterial wilt</td><td><span className="pill pill-r">High</span></td><td><span className="pill pill-g">Confirmed</span></td><td><div className="act-btns"><button className="ab" style={{ background: '#dbeafe', color: '#2563eb' }}>👁</button></div></td></tr>
                  <tr><td><div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><div className="fav">IU</div><div><div style={{ fontSize: '8px', fontWeight: '500' }}>Immaculée Umubyeyi</div><div style={{ fontSize: '7px', color: '#94a3b8' }}>APT-004</div></div></div></td><td>Rulindo</td><td>Potatoes</td><td>Late blight</td><td><span className="pill pill-r">High</span></td><td><span className="pill pill-y">Pending</span></td><td><div className="act-btns"><button className="ab" style={{ background: '#dcfce7', color: '#15803d' }}>✓</button><button className="ab" style={{ background: '#fee2e2', color: '#dc2626' }}>✗</button></div></td></tr>
                </tbody></table>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                <div className="dcard"><div className="dcard-head"><h3>Overview</h3></div><div className="donut-area"><svg width="90" height="90" viewBox="0 0 90 90" style={{ display: 'block', margin: '0 auto' }}><circle cx="45" cy="45" r="32" fill="none" stroke="#dcfce7" strokeWidth="13" /><circle cx="45" cy="45" r="32" fill="none" stroke="#15803d" strokeWidth="13" strokeDasharray="108 93" strokeDashoffset="0" /><circle cx="45" cy="45" r="32" fill="none" stroke="#f59e0b" strokeWidth="13" strokeDasharray="38 163" strokeDashoffset="-108" /><circle cx="45" cy="45" r="32" fill="none" stroke="#3b82f6" strokeWidth="13" strokeDasharray="57 144" strokeDashoffset="-146" /><circle cx="45" cy="45" r="32" fill="none" stroke="#ef4444" strokeWidth="13" strokeDasharray="16 185" strokeDashoffset="-203" /><text x="45" y="42" textAnchor="middle" fontSize="11" fontWeight="500" fill="var(--color-text-primary)">69</text><text x="45" y="51" textAnchor="middle" fontSize="7" fill="var(--color-text-secondary)">Total</text></svg><div className="donut-legend"><div className="dl-row"><span className="dl-dot" style={{ background: '#15803d' }}></span><span className="dl-lbl">Completed</span><span className="dl-val">34</span></div><div className="dl-row"><span className="dl-dot" style={{ background: '#f59e0b' }}></span><span className="dl-lbl">Pending</span><span className="dl-val">12</span></div><div className="dl-row"><span className="dl-dot" style={{ background: '#3b82f6' }}></span><span className="dl-lbl">Confirmed</span><span className="dl-val">18</span></div><div className="dl-row"><span className="dl-dot" style={{ background: '#ef4444' }}></span><span className="dl-lbl">Cancelled</span><span className="dl-val">5</span></div></div></div></div>
                <div className="dcard"><div className="dcard-head"><h3>Schedule Today</h3></div><div className="sched-list"><div className="sched-item" style={{ background: '#eff6ff', borderColor: '#3b82f6' }}><span className="sched-time" style={{ color: '#1d4ed8' }}>08:00</span><div><div className="sched-name" style={{ color: '#1e40af' }}>Claudine Mukamana</div><div className="sched-type" style={{ color: '#3b82f6' }}>Field Visit · Gasabo</div></div></div><div className="sched-item" style={{ background: '#f0fdf4', borderColor: '#15803d' }}><span className="sched-time" style={{ color: '#14532d' }}>10:30</span><div><div className="sched-name" style={{ color: '#14532d' }}>Emmanuel Habimana</div><div className="sched-type" style={{ color: '#15803d' }}>Consultation · Kicukiro</div></div></div><div className="sched-item" style={{ background: '#fefce8', borderColor: '#ca8a04' }}><span className="sched-time" style={{ color: '#92400e' }}>14:00</span><div><div className="sched-name" style={{ color: '#78350f' }}>Vestine Nyirahabimana</div><div className="sched-type" style={{ color: '#ca8a04' }}>Follow-up · Nyarugenge</div></div></div><div className="sched-item" style={{ background: '#faf5ff', borderColor: '#9333ea' }}><span className="sched-time" style={{ color: '#6b21a8' }}>16:30</span><div><div className="sched-name" style={{ color: '#581c87' }}>Group Training</div><div className="sched-type" style={{ color: '#9333ea' }}>Workshop · Bugesera</div></div></div></div></div>
              </div>
            </div>
            <div className="dash-grid2">
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                <div className="dcard"><div className="dcard-head"><h3>Reports by District</h3></div><div className="bar-list"><div className="bar-row"><span className="bar-lbl">Musanze</span><div className="bar-track"><div className="bar-fill" style={{ width: '100%' }}></div></div><span className="bar-num">27</span></div><div className="bar-row"><span className="bar-lbl">Bugesera</span><div className="bar-track"><div className="bar-fill" style={{ width: '81%' }}></div></div><span className="bar-num">22</span></div><div className="bar-row"><span className="bar-lbl">Gasabo</span><div className="bar-track"><div className="bar-fill" style={{ width: '67%' }}></div></div><span className="bar-num">18</span></div><div className="bar-row"><span className="bar-lbl">Rulindo</span><div className="bar-track"><div className="bar-fill" style={{ width: '56%' }}></div></div><span className="bar-num">15</span></div><div className="bar-row"><span className="bar-lbl">Kicukiro</span><div className="bar-track"><div className="bar-fill" style={{ width: '44%' }}></div></div><span className="bar-num">12</span></div></div></div>
                <div className="dcard"><div className="dcard-head"><h3>Recent Reports</h3></div><table className="dtable"><thead><tr><th>Farmer</th><th>Crop</th><th>Issue</th><th>District</th><th>Severity</th><th>Status</th></tr></thead><tbody><tr><td>Jean-Baptiste Nkusi</td><td>Maize</td><td>Fall Armyworm</td><td>Musanze</td><td><span className="pill pill-r">High</span></td><td><span className="pill pill-g">Resolved</span></td></tr><tr><td>Aline Mukamutesi</td><td>Beans</td><td>Angular leaf spot</td><td>Rwamagana</td><td><span className="pill pill-y">Medium</span></td><td><span className="pill pill-b">In Progress</span></td></tr><tr><td>Théogène Habiyaremye</td><td>Wheat</td><td>Yellow rust</td><td>Nyabihu</td><td><span className="pill pill-r">High</span></td><td><span className="pill pill-y">Pending</span></td></tr></tbody></table></div>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                <div className="dcard"><div className="dcard-head"><h3>Severity Overview</h3></div><div className="sev-bars"><div><div className="sev-row"><span>High</span><span>28 (28%)</span></div><div className="prog"><div className="prog-fill" style={{ width: '28%', background: '#ef4444' }}></div></div></div><div><div className="sev-row"><span>Medium</span><span>45 (45%)</span></div><div className="prog"><div className="prog-fill" style={{ width: '45%', background: '#f59e0b' }}></div></div></div><div><div className="sev-row"><span>Low</span><span>27 (27%)</span></div><div className="prog"><div className="prog-fill" style={{ width: '27%', background: '#15803d' }}></div></div></div></div></div>
                <div className="dcard"><div className="dcard-head"><h3>Quick Actions</h3></div><div className="qa-grid"><button className="qa" style={{ background: '#15803d' }}>📄 Write Report</button><button className="qa" style={{ background: '#2563eb' }}>👤 Add Farmer</button><button className="qa" style={{ background: '#7c3aed' }}>📍 Schedule Visit</button><button className="qa" style={{ background: '#d97706' }}>📚 Knowledge Base</button></div></div>
              </div>
            </div>
            <div className="dash-grid3">
              <div className="dcard"><div className="dcard-head"><h3>Latest Notifications</h3></div><div className="notif-list"><div className="ni unr"><div className="ni-icon" style={{ background: '#fee2e2' }}>🔔</div><div><div className="ni-title">High severity case reported</div><div className="ni-msg">Late blight outbreak in Rulindo — 3 farms affected</div><div className="ni-time">5 min ago</div></div></div><div className="ni unr"><div className="ni-icon" style={{ background: '#dbeafe' }}>💬</div><div><div className="ni-title">New appointment request</div><div className="ni-msg">Claudine Mukamana requested a field visit for maize disease</div><div className="ni-time">22 min ago</div></div></div><div className="ni"><div className="ni-icon" style={{ background: '#dcfce7' }}>📄</div><div><div className="ni-title">Report submitted</div><div className="ni-msg">Emmanuel Habimana submitted a new farm report on root rot</div><div className="ni-time">1 hr ago</div></div></div></div></div>
              <div className="dcard"><div className="dcard-head"><h3>Knowledge Base</h3></div><div className="kb-list"><div className="kb-item"><div className="kb-icon">📖</div><div><div className="kb-t">Integrated Pest Management for Maize</div><div className="kb-c">Pests & Diseases</div><div className="kb-m"><span>342 reads</span><span>3 days ago</span></div></div></div><div className="kb-item"><div className="kb-icon">🌱</div><div><div className="kb-t">Soil Health & pH Management in Rwanda</div><div className="kb-c">Soil Science</div><div className="kb-m"><span>218 reads</span><span>1 week ago</span></div></div></div><div className="kb-item"><div className="kb-icon">🥔</div><div><div className="kb-t">Late Blight Control in Irish Potatoes</div><div className="kb-c">Disease Control</div><div className="kb-m"><span>489 reads</span><span>2 days ago</span></div></div></div></div></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}